version: "3.9"
services:
  app:
    build: .
    command: yarn start
    volumes:
      - .:/usr/app/
      # - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on: [ dynamodb-init ]
  dynamo:
    image:  amazon/dynamodb-local
    hostname: dynamodb
    restart: always
    ports:
      - 8000:8000
    expose:
      - "8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
  dynamodb-init:
    image: node:14
    working_dir: /work
    volumes: [ ".:/work" ]
    command: [ scripts/init.sh ]
    depends_on: [ dynamo ]